/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-05 09:11:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mid;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mid_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>중단 만들기</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/js/mid.js\"></script>\r\n");
      out.write("<script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"special_box\" style=\"\">\r\n");
      out.write("				<div class=\"bg\" style=\"background: rgb(244, 244, 244);\"></div>\r\n");
      out.write("				<div class=\"cont\">\r\n");
      out.write("					<em class=\"tag\">EVENT ♥</em>\r\n");
      out.write("					<h2 class=\"mtit\"><a href=\"javascript:mainLogAndMove('b1f1d84c-e1cf-11ed-b570-0242ac1b0002','https://korean.visitkorea.or.kr/list/travelinfo.do?service=event');\">국내 여행! <br> 풍성한 혜택이 가득</a></h2>\r\n");
      out.write("					<p class=\"stit\">아름다운 대한민국 구석구석으로 떠나보세요! </p>\r\n");
      out.write("					<span class=\"day\">2023. 10. 27. ~ 2023. 12. 31.</span>\r\n");
      out.write("					<span class=\"img\"><img src=\"../resources/images/img2.jpg\" alt=\"국내 여행! <br> 풍성한 혜택이 가득\"></span>\r\n");
      out.write("					<div class=\"list\">\r\n");
      out.write("						<div class=\"menu type1\">\r\n");
      out.write("							<div class=\"swiper-container swiper-container-initialized swiper-container-horizontal\">\r\n");
      out.write("								<div class=\"swiper-wrapper\" style=\"transition-duration: 0ms; transform: translate3d(305.211px, 0px, 0px);\"><div class=\"swiper-slide on swiper-slide-active\" style=\"margin-right: 10px;\"><a href=\"javascript:;\" onclick=\"pavilion.changeTab(this);\">국내여행 이벤트 &amp; 혜택 모아보기</a></div></div>\r\n");
      out.write("								<div class=\"swiper-button-prev swiper-button-disabled swiper-button-lock\" tabindex=\"0\" role=\"button\" aria-label=\"Previous slide\" aria-disabled=\"true\">이전</div>\r\n");
      out.write("								<div class=\"swiper-button-next swiper-button-disabled swiper-button-lock\" tabindex=\"0\" role=\"button\" aria-label=\"Next slide\" aria-disabled=\"true\">다음</div>\r\n");
      out.write("							<span class=\"swiper-notification\" aria-live=\"assertive\" aria-atomic=\"true\"></span></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<ul class=\"banner\">\r\n");
      out.write("						<li class=\"swiper-container swiper-container-initialized swiper-container-horizontal\" style=\"visibility: visible; left: -9999px;\">\r\n");
      out.write("					<div class=\"swiper-wrapper\" style=\"transform: translate3d(0px, 0px, 0px); transition-duration: 0ms;\"><div class=\"swiper-slide swiper-slide-active\" style=\"margin-right: 20px;\"><a href=\"javascript:mainLogAndMove('b1f1d84c-e1cf-11ed-b570-0242ac1b0002', 'https://korean.visitkorea.or.kr/detail/event_detail.do?cotid=b092e429-e505-48a3-9b43-5084658b3427')\">\r\n");
      out.write("						<img src=\"../resources/images/pic1.jpg\" alt=\"undefined\"></a></div><div class=\"swiper-slide swiper-slide-next\" style=\"margin-right: 20px;\"><a href=\"javascript:mainLogAndMove('b1f1d84c-e1cf-11ed-b570-0242ac1b0002', 'https://korean.visitkorea.or.kr/detail/event_detail.do?cotid=cf339089-e4ab-4f4b-a205-006fb3b09d41')\">\r\n");
      out.write("						<img src=\"../resources/images/pic2.jpg\" alt=\"undefined\"></a></div><div class=\"swiper-slide\" style=\"margin-right: 20px;\"><a href=\"javascript:mainLogAndMove('b1f1d84c-e1cf-11ed-b570-0242ac1b0002', 'https://korean.visitkorea.or.kr/detail/event_detail.do?cotid=2998197e-5c52-471b-a4e0-a1a33e73f3ee')\">\r\n");
      out.write("						<img src=\"../resources/images/pic3.jpg\" alt=\"undefined\"></a></div><div class=\"swiper-slide\" style=\"margin-right: 20px;\"><a href=\"javascript:mainLogAndMove('b1f1d84c-e1cf-11ed-b570-0242ac1b0002', 'https://korean.visitkorea.or.kr/detail/event_detail.do?cotid=bd62967c-6db0-46dd-8935-074dde6329c7')\">\r\n");
      out.write("						<img src=\"../resources/images/pic4.jpg\" alt=\"undefined\"></a></div><div class=\"swiper-slide\" style=\"margin-right: 20px;\"><a href=\"javascript:mainLogAndMove('b1f1d84c-e1cf-11ed-b570-0242ac1b0002', '/detail/detail_view.do?cotid=61d08596-f772-48f6-876a-250b4e3e3f68')\">\r\n");
      out.write("						<img src=\"../resources/images/pic5.jpg\" alt=\"디지털 관광주민증과 함께 여행이 있는 주말, 혜택 더 있는 주말!\"></a></div><div class=\"swiper-slide\" style=\"margin-right: 20px;\"><a href=\"javascript:mainLogAndMove('b1f1d84c-e1cf-11ed-b570-0242ac1b0002', 'https://korean.visitkorea.or.kr/detail/event_detail.do?cotid=bd71641c-eaf2-4f64-90d9-b36b6ee4f4a7')\">\r\n");
      out.write("						<img src=\"../resources/images/pic6.jpg\" alt=\"undefined\"></a></div><div class=\"swiper-slide\" style=\"margin-right: 20px;\"><a href=\"javascript:mainLogAndMove('b1f1d84c-e1cf-11ed-b570-0242ac1b0002', 'https://korean.visitkorea.or.kr/detail/event_detail.do?cotid=c901e21a-ccba-4a80-8e0c-4d860aa1133d')\">\r\n");
      out.write("						<img src=\"../resources/images/pic7.jpg\"alt=\"undefined\"></a></div></div>\r\n");
      out.write("						<div class=\"swiper-button-prev swiper-button-disabled\" tabindex=\"0\" role=\"button\" aria-label=\"Previous slide\" aria-disabled=\"true\">이전</div>\r\n");
      out.write("						<div class=\"swiper-button-next\" tabindex=\"0\" role=\"button\" aria-label=\"Next slide\" aria-disabled=\"true\">다음</div>\r\n");
      out.write("					<span class=\"swiper-notification\" aria-live=\"assertive\" aria-atomic=\"true\"></span></li></ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
